# Generated by Django 4.0.3 on 2022-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='fliamoyano',
        ),
    ]
